# Site settings
title: Graveyard Bean - growing coffee in graveyard soil
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "http://graveyardbean.com"
url: "http://graveyardbean.com"
twitter_username: graveyardbean

# Build settings
markdown: kramdown
permalink: pretty
