# Site settings
title: Bosslee Coffee - Producing The Best Cold Brew In Singapore
email: your-email@domain.com
description: "We love coffee, we love it both hot and cold. One day, we mixed our own blend and produced a cold brew that is so good that we believe you will love it too."
baseurl: ""
url: "http://bossleecoffee.com"
twitter_username: bossleecoffee

# Build settings
markdown: kramdown
permalink: pretty
